port : 8080
host : "localhost"
temp_dir_name : "murocami-temp"
input_point : "cmd/main.go"
output_point : "bin/app"
scp_for_cd : false
send_notify : false
save_history : false
file_history : history.json
notify_chat_id : -12345567