port: "8080"
host: "localhost"
static_dir: "/static"
temp_dir_name: "temp"
input_point: "cmd/main.go"
output_point: "bin/app"
scp_for_cd: false
use_ui: true
notify:
  send: false 
  chat_id: 123456789
  token: "dummy_token"
nagent:
  use : true
  host: "localhost"
  port: 50051
