// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/network_agent_client/proto/nagent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkAgent_SetTask_FullMethodName = "/NetworkAgent/SetTask"
)

// NetworkAgentClient is the client API for NetworkAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkAgentClient interface {
	SetTask(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResp], error)
}

type networkAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkAgentClient(cc grpc.ClientConnInterface) NetworkAgentClient {
	return &networkAgentClient{cc}
}

func (c *networkAgentClient) SetTask(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkAgent_ServiceDesc.Streams[0], NetworkAgent_SetTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkRequest, StreamResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkAgent_SetTaskClient = grpc.ServerStreamingClient[StreamResp]

// NetworkAgentServer is the server API for NetworkAgent service.
// All implementations must embed UnimplementedNetworkAgentServer
// for forward compatibility.
type NetworkAgentServer interface {
	SetTask(*WorkRequest, grpc.ServerStreamingServer[StreamResp]) error
	mustEmbedUnimplementedNetworkAgentServer()
}

// UnimplementedNetworkAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkAgentServer struct{}

func (UnimplementedNetworkAgentServer) SetTask(*WorkRequest, grpc.ServerStreamingServer[StreamResp]) error {
	return status.Errorf(codes.Unimplemented, "method SetTask not implemented")
}
func (UnimplementedNetworkAgentServer) mustEmbedUnimplementedNetworkAgentServer() {}
func (UnimplementedNetworkAgentServer) testEmbeddedByValue()                      {}

// UnsafeNetworkAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkAgentServer will
// result in compilation errors.
type UnsafeNetworkAgentServer interface {
	mustEmbedUnimplementedNetworkAgentServer()
}

func RegisterNetworkAgentServer(s grpc.ServiceRegistrar, srv NetworkAgentServer) {
	// If the following call pancis, it indicates UnimplementedNetworkAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkAgent_ServiceDesc, srv)
}

func _NetworkAgent_SetTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkAgentServer).SetTask(m, &grpc.GenericServerStream[WorkRequest, StreamResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkAgent_SetTaskServer = grpc.ServerStreamingServer[StreamResp]

// NetworkAgent_ServiceDesc is the grpc.ServiceDesc for NetworkAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NetworkAgent",
	HandlerType: (*NetworkAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetTask",
			Handler:       _NetworkAgent_SetTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/network_agent_client/proto/nagent.proto",
}
